### ISSUE TITLE
details.php: Use of undefined constant download

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/pip-db#104]
```
Notice: Use of undefined constant download - assumed 'download' in /var/www/details.php on line 15 Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'A template that extends another one cannot have a body in "details.html" at line 1.' in /var/www/lib/Twig/Parser.php:370 Stack trace: #0 /var/www/lib/Twig/Parser.php(383): Twig_Parser->filterBodyNodes(Object(Twig_Node_Text)) #1 /var/www/lib/Twig/Parser.php(98): Twig_Parser->filterBodyNodes(Object(Twig_Node)) #2 /var/www/lib/Twig/Environment.php(507): Twig_Parser->parse(Object(Twig_TokenStream)) #3 /var/www/lib/Twig/Environment.php(559): Twig_Environment->parse(Object(Twig_TokenStream)) #4 /var/www/lib/Twig/Environment.php(331): Twig_Environment->compileSource('
```

**Comment by ChrisCummins** [comment]
Fixed.
