### ISSUE TITLE
results.php: Twig Error Syntax exception

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/pip-db#105]
```
Fatal error: Uncaught exception 'Twig_Error_Syntax' with message 'A template that extends another one cannot have a body in "results.html" at line 15.' in /var/www/lib/Twig/Parser.php:370 Stack trace: #0 /var/www/lib/Twig/Parser.php(383): Twig_Parser->filterBodyNodes(Object(Twig_Node_Text)) #1 /var/www/lib/Twig/Parser.php(98): Twig_Parser->filterBodyNodes(Object(Twig_Node)) #2 /var/www/lib/Twig/Environment.php(507): Twig_Parser->parse(Object(Twig_TokenStream)) #3 /var/www/lib/Twig/Environment.php(559): Twig_Environment->parse(Object(Twig_TokenStream)) #4 /var/www/lib/Twig/Environment.php(331): Twig_Environment->compileSource('{% extends "_pa...', 'results.html') #5 /var/www/lib/template.php(61): Twig_Environment->loadTemplate('results.html') #6 /var/www/lib/template.php(79): pip_template_get_template('results') #7 /var/www/results.php(239): pip_render_template('results', Array) #8 {main} thrown in /var/www/lib/Twig/Parser.php on line 370
```

**Comment by ChrisCummins** [comment]
Fixed.
